Zigbee client fixes
madchicken/homebridge-zigbee-nt pull request #226
Opened 2022-01-04 19:07 UTC by maccoylton

Update "supports" function to allow for accessories with nested features, for example in a TVR, climate is a feature that contains a number of features. array.find  doesn't search through nested arrays. 

Also note the original does a comparison to null, where as the definition of array.find says it returns undefined if it doesn't find anything,   so in my testing it wasn't functioning properly anyway.

2022-01-13 13:59 UTC, madchicken requested changes

2022-01-13 13:59 UTC, madchicken commented on src/accessories/zig-bee-accessory.ts
> +      //      this.log.debug(
Can you remove comments please?

2022-01-30 19:36 UTC, maccoylton commented
comments removed as requested

2022-01-30 19:45 UTC, madchicken approved these changes

2022-01-30 19:45 UTC, merged