Adding RWL021 Philips Hue Dimmable Switch compatibility
madchicken/homebridge-zigbee-nt pull request #87
Opened 2021-01-20 14:36 UTC by Armageddon95

I can't test the code yet. Please try it.

2021-01-20 16:29 UTC, madchicken requested changes

2021-01-20 16:29 UTC, madchicken commented on src/accessories/philips/philips-hue-dimmable-switch.ts
> +
I don't think this switch/case is right. Reading the description page [here](https://www.zigbee2mqtt.io/devices/324131092621.html#action-enum) I see different actions exposed by this device

2021-01-20 16:29 UTC, madchicken commented on src/index.ts
> +    ['RWL021'],
I think you should use `324131092621` as model here

2021-01-23 22:09 UTC, tr1ng0 commented on src/accessories/philips/philips-hue-dimmable-switch.ts
> +
@Armageddon95 do you need help with the pull request? Madchicken is correct with those request changes

2021-02-09 14:35 UTC, madchicken commented
Closing stale PR

2021-02-09 14:35 UTC, closed without merging